"""
ESGenuine — deterministic-layer COST harness
============================================

The paper quotes a per-claim cost for the repair layer ("0.58 ms/claim, 218 ms for a
373-claim report") and the reproducibility section claims every reported number
recomputes from committed fixtures. That was true of every number except this one:
no script produced it. This closes that gap.

WHAT IS TIMED — and what deliberately is not
--------------------------------------------
Timed: the deterministic stack only, i.e. exactly the transformation `run_ablation`
calls S1..S5 — ontology normalisation, key refresh, FY-column repair, value-in-source
verification, gate corrections and the furniture filter.

NOT timed, on purpose:
  * the LLM call (the point of the measurement is that this layer avoids one),
  * PDF parsing / Docling (upstream of the layer, and cached),
  * `deepcopy` of the input claims (a harness artifact, not production work),
  * JSON load of the fixtures.

Single-threaded, no network, no API spend. The claim being supported is "this layer is
free relative to a second LLM pass", so an honest measurement excludes everything that
is not the layer.

Run:
    python backend/scripts/run_cost.py
    python backend/scripts/run_cost.py --repeats 20 --markdown
"""
import argparse
import copy
import json
import statistics
import sys
import time
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO / "backend" / "src"))
sys.path.insert(0, str(_REPO / "backend" / "scripts"))

from run_ablation import CASES, _load, _run_stage        # noqa: E402


def measure(fixture: str, cache: str, repeats: int) -> dict:
    claims, md_by_page = _load(fixture, cache)

    # Warm-up: first call imports/JITs the ontology tables and compiles the gate's
    # regexes. Including it would attribute one-time setup to per-claim cost.
    _run_stage(5, claims, md_by_page)

    samples = []
    for _ in range(repeats):
        # deepcopy OUTSIDE the timed region — _run_stage copies internally, but the
        # cost we are claiming is the layer's, not the harness's isolation strategy.
        work = copy.deepcopy(claims)
        t0 = time.perf_counter()
        kept = _run_stage(5, work, md_by_page)
        samples.append(time.perf_counter() - t0)

    n_in = len(claims)
    best = min(samples)                     # min, not mean: the floor is the signal;
    med = statistics.median(samples)        # anything above it is scheduler noise
    return {
        "claims_in": n_in, "claims_out": len(kept), "repeats": repeats,
        "total_ms_min": 1000 * best, "total_ms_median": 1000 * med,
        "total_ms_stdev": 1000 * (statistics.stdev(samples) if len(samples) > 1 else 0.0),
        "per_claim_ms_min": 1000 * best / n_in,
        "per_claim_ms_median": 1000 * med / n_in,
    }


def run(repeats: int) -> dict:
    return {label: {"fixture": fixture, **measure(fixture, cache, repeats)}
            for label, fixture, cache, _gold in CASES}


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Time the deterministic repair layer (S1..S5).")
    ap.add_argument("--repeats", type=int, default=10)
    ap.add_argument("--markdown", action="store_true")
    ap.add_argument("--json", dest="json_out")
    a = ap.parse_args()

    res = run(a.repeats)

    if a.markdown:
        print("\n<!-- generated by backend/scripts/run_cost.py — do not hand-edit -->\n")
        print("| document | claims in | claims out | layer runtime (ms) | per claim (ms) |")
        print("|---|--:|--:|--:|--:|")
        for label, d in res.items():
            print(f"| {label} | {d['claims_in']} | {d['claims_out']} | "
                  f"{d['total_ms_min']:.0f} | **{d['per_claim_ms_min']:.2f}** |")
        print(f"\nBest of {a.repeats} runs, single-threaded, no network. Excludes the LLM "
              f"call, PDF parsing and harness-only deep copies — see the module docstring.")
    else:
        for label, d in res.items():
            print(f"\n{'=' * 78}\n{label}\n{'=' * 78}")
            print(f"  claims in / out    : {d['claims_in']} -> {d['claims_out']}")
            print(f"  repeats            : {d['repeats']}")
            print(f"  layer runtime      : {d['total_ms_min']:.1f} ms min | "
                  f"{d['total_ms_median']:.1f} ms median | sd {d['total_ms_stdev']:.1f}")
            print(f"  PER CLAIM          : {d['per_claim_ms_min']:.3f} ms min | "
                  f"{d['per_claim_ms_median']:.3f} ms median")
        print("\n  Timed: ontology + key refresh + FY repair + value-in-source + gate +")
        print("  furniture filter. NOT timed: LLM call, PDF parse, harness deep copies.")

    if a.json_out:
        Path(a.json_out).write_text(json.dumps(res, indent=2), encoding="utf-8")
        print(f"\nwrote {a.json_out}")
